export {default as Footer} from './Footer'
export { default as Footer } from './Cart'
export { default as Footer } from './Footer'
export { default as Footer } from './Footer'
export { default as Footer } from './Footer'
export { default as Footer } from './Footer'